package com.mycompany.myapp;


import static com.codename1.ui.CN.*;
import com.codename1.ui.Display;
import com.codename1.ui.Form;
import com.codename1.ui.Dialog;
import com.codename1.ui.Label;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.io.Log;
import com.codename1.ui.Toolbar;
import java.io.IOException;
import com.codename1.ui.layouts.BoxLayout;
import com.codename1.io.NetworkEvent;
import com.codename1.ui.FontImage;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {

    private Form current;
    private Resources theme;

    public void init(Object context) {
        // use two network threads instead of one
        updateNetworkThreadCount(2);

        theme = UIManager.initFirstTheme("/theme");

        // Enable Toolbar on all Forms by default
        Toolbar.setGlobalToolbar(true);

        // Pro only feature
        Log.bindCrashProtection(true);

        addNetworkErrorListener(err -> {
            // prevent the event from propagating
            err.consume();
            if(err.getError() != null) {
                Log.e(err.getError());
            }
            Log.sendLogAsync();
            Dialog.show("Connection Error", "There was a networking error in the connection to " + err.getConnectionRequest().getUrl(), "OK", null);
        });        
    }
    
    public void start() {
        if(current != null){
            current.show();
            return;
        }
        Form acceuil = new Form("Hi World", BoxLayout.y());
        Form F1 = new Form("Page 1");
        Form F2 = new Form("Page 2");
        Form F3 = new Form("Page 3");
        acceuil.getToolbar().addCommandToSideMenu("Page 1", null, ev-> F1.show());
        acceuil.getToolbar().addCommandToSideMenu("Page 2", null, ev-> F2.show());
        acceuil.getToolbar().addCommandToSideMenu("Page 3", null, ev-> F3.show());
        F1.getToolbar().addMaterialCommandToLeftBar("back", FontImage.MATERIAL_ARROW_BACK, ev -> acceuil.showBack());
        F2.getToolbar().addCommandToRightBar("back", null, ev -> acceuil.showBack());
        F3.getToolbar().addCommandToOverflowMenu("back", null, ev -> acceuil.showBack());
        F3.getToolbar().addMaterialCommandToOverflowMenu("exit", FontImage.MATERIAL_EXIT_TO_APP, ev -> Display.getInstance().exitApplication());
        acceuil.show();
    }

    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }
    
    public void destroy() {
    }

}
